from .animal import Animal
from .llama import Llama
from .goat import Goat
from .donkey import Donkey
from .pony import Pony
from .alpaca import Alpaca
from .copperhead import CopperHead
from .king_cobra import KingCobra
from .rat_snake import RatSnake
from .cottonmouth import Cottonmouth
from .giant_anaconda import GiantAnaconda
from .goldfish import GoldFish
from .stonefish import StoneFish
from .mallard import Mallard
from .blue_ringed_octopus import BlueRingedOctopus
from .box_jellyfish import BoxJellyfish